### PR TITLE
Try to add macos build

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@scopatz, I think the macos problems are resolved by adding the sysroot. However, I may be missing something, so if this is not the right fix, please let me know.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
This PR suffers from the openssl3 problem with `ERR_GET_FUNC` that is addressed by #5. Once that PR is in, this one can be rebased and should go through.

**Comment by pkgw** [comment]
This is now superseded by #6, which has been rebased onto the latest `main`. @zklaus, if you still want to be added as a maintainer, let me know and I'll add that to the other PR.

**Pull request closed without merging**
