### PR TITLE
Add patches for openssl3 compatibility

### LINKED ISSUE #4: serf is not fully compatible with openssl3
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

serf makes use of the openssl macro `ERR_GET_FUNC`, but this has been removed (see [the openssl changelog](https://www.openssl.org/news/changelog.html), search for ERR_GET_FUNC). This is a known issue, see the serf JIRA tracker [here](https://issues.apache.org/jira/projects/SERF/issues/SERF-202?filter=allopenissues) and [here](https://issues.apache.org/jira/projects/SERF/issues/SERF-198?filter=allopenissues).

The fix seems to be twofold: First, remove the use of `ERR_GET_FUNC` (which only occurs in buckets/ssl_buckets.c); second, fix the bug that triggers the error see [serf.patch](https://issues.apache.org/jira/secure/attachment/13019945/serf.patch).

The current situation creates problems downstream in subversion, where `svn` fails with
```
$SRC_DIR/subversion/svn/.libs/lt-svn: symbol lookup error: $PREFIX/lib/libserf-1.so.1: undefined symbol: ERR_GET_FUNC
```
see build log [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=477887&view=logs&j=aadbb858-7e4f-5355-cf11-539b554fa842&t=c85b731f-0b39-5171-bac7-cd58a8cdd84d&l=1200).

### Installed packages

```shell
build issue
```

### Environment info

```shell
CI environment
```

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #4

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
There are a number of failures in the tests, but they seem unrelated to the problem here. Rather, the tests seem broken upstream, see https://issues.apache.org/jira/projects/SERF/issues/SERF-202?filter=allopenissues.

I believe that the patches in this PR already improve the situation and will allow building subversion with openssl3.

**Comment by zklaus** [comment]
@hmaarrfk, since you took care of the automatic openssl3 migration PR, would you be willing to have a look?

**Comment by hmaarrfk** [comment]
Are you able to selectively skip the tests. Run then if ssl is 1?

**Comment by hmaarrfk** [comment]
i think @scopatz should likely give you a first review. Ping if he doesn't respond withing 7 days

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
It looks like #2 was merged just before this PR, so I guess there was something broken and you tried to fix it @zklaus?

BTW, found an upstream [issue](https://issues.apache.org/jira/browse/SERF-202) (still open) for openssl 3 support.

**Comment by pkgw** [comment]
Superseded by #7.

**Pull request closed without merging**
